[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = [
	"-O2",
	"-fsanitize=address",
	"-fsanitize=undefined",
	"-std=c++17",
	"-D_GLIBCXX_DEBUG",
	"-D_GLIBCXX_DEBUG_PEDANTIC",
	"-fstack-protector",
	"-D_FORTIFY_SOURCE=2",
]
