name: test_all_code

on: push

jobs:
  library_checker_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper
    - name: Set up Rust (1.42.0)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
    # required by cargo-udeps
    - name: Set up Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all

  stress_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bc
      run: sudo apt-get install bc
    - name: Run stress tests
      run: make --directory=tests/ test

  test_compiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run compiles
      run: make --directory=tests/ test_compiles

  check_code_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install astyle
      run: sudo apt-get install astyle
    - name: Check code format
      run: make --directory=tests/ test_format

  check_snake_case:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check snake case
      run: make --directory=tests/ check_snake_case
