name: test_all_code

on: push

jobs:
  online_judge_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper
    - name: Set up Rust (1.42.0)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
    # required by cargo-udeps
    - name: Set up Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
    - name: Set up kactl submodule
      run: git submodule init && git submodule update && cd ac-library/atcoder && ln -s . atcoder
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all

  check_format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install astyle clang cppcheck
    - name: Check snake case and lint
      run: make --directory=tests/ check_format

  compile_all_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Compile all tests
      run: make --directory=tests/ compile_all_tests

  tests_by_modification:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Compile all tests
      run: ./tests/scripts/tests_by_git_modification.sh
