name: trigger tests scheduled

on:
  schedule:
    # So what happens is sometimes, I'll do some code mod style change which
    # touches many files. This then requires all those tests to be re-run, but
    # the verification-helper tool has a 10 minute timeout.
    #
    # https://github.com/online-judge-tools/verification-helper/blob/master/onlinejudge_verify/main.py#L75
    #
    # So only around 5-10 tests run per commit, leaving un-run tests. This cron
    # job solves this by reruning any remaining tests every 30 minutes.
    - cron:  '5,35 7-12 * * *'

jobs:
  trigger_tests_scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: trigger run tests scheduled
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh workflow run 'run tests scheduled' --ref dev
